[package]
name = "raytracer"
version = "0.1.0"
authors = ["pb"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23"
indicatif = "0.15"
rand = "0.7"
rayon = "1.5"
